#!/bin/bash

odin build ./src \
  -thread-count:8 \
  -show-timings \
  -vet \
  -vet-cast \
  -vet-semicolon \
  -vet-unused \
  -vet-unused-imports \
  -vet-unused-variables \
  -vet-using-param \
  -vet-using-stmt \
  -warnings-as-errors \
  -disallow-do \
  -no-bounds-check \
  -no-type-assert \
  -o:speed \
  -out:build/termsfx
